mysite/URL/urls.py
from . import views
from django.urls import path

app_name = 'URLs'
urlpatterns = [

    path('', views.URL, name='URLhomepage'),
    path('<str:URLstr>/', views.URLstr, name='URLstr'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, re_path
from URL import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('URL.urls')),  
]








mysite/URL/models.py
from django.db import models

class URLPattern (models.Model):
    longURL = models.CharField(max_length=1000)
    shortURL = models.CharField(max_length=200, blank=True)
    visits = models.IntegerField(default=0)
    def __str__(self):
        return str(self.longURL) + " | " + str(self.shortURL) + " | Visits: " + str(self.visits)

mysite/URL/views.py
from django.shortcuts import render
from .models import URLPattern

#View function of homepage (accessed when no further pattern is provided after the main website URL)
def URL(request):
    searched = None   #initialized to none (no input in input bar) 

    if(request.GET.get('searchBtn')):  #checks if value is entered into input bar and submitted
        URL_Map = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        searched = request.GET['searchBox']   #retrieve long URL value from search bar

        #check duplicate
        selectedURL = URLPattern.objects.filter(longURL=searched)
        if (len(selectedURL)!=0):       #catches duplicate and displays message
            context = {
                'selectedURL': selectedURL,
                'searched': searched,
                'URLTyped': True,
                'duplicate': True,
            }
            return render(request, 'homePage.html', context)

        #create database entry if no duplicate found
        selectedURL = URLPattern.objects.create(longURL=searched)
        selectedID = selectedURL.id
        #need to convert long URL through the use of the database ID to a order of 62 number such that URL_Map can be used to map correspond values

        #find numerical value of entered input
        accum = 0
        for i in searched:
            accum = accum + ord(i)
        int(accum)

        #find shortened mapped value
        shortURL = ''
        while (accum !=0):
            remainder = accum % 62
            shortURL = shortURL + URL_Map[int(remainder)]
            accum = (accum - remainder)/62

        #shortURL now stores the value of the converted short URL
        #Queryset for newly created URL pattern and send data to template for display
        URLPattern.objects.filter(id=selectedID).update(shortURL=shortURL)
        selectedURL = URLPattern.objects.get(id=selectedID)
        context = {
            'selectedURL': selectedURL,
            'searched': searched,
            'URLTyped': True,
            'shortenedURL': shortURL,
            'duplicate': False,
        }
        return render(request, 'homePage.html', context)

    #if no URL is typed into search bar (ie. homepage reached by just www.example.com)
    context = {
        'searched': searched,
        'URLTyped': False,
        'duplicate': False,
    }

    return render(request, 'homePage.html', context)


#View function to arrive to a given URL given the long or short URL pattern
def URLstr(request, URLstr):
    notFound = False

    #try to find short URL submitted
    selectedURL = URLPattern.objects.filter(longURL=URLstr).order_by().distinct()
    if len(selectedURL) == 0: #if short URL not found, check whether long URL inputted instead
        selectedURL = URLPattern.objects.filter(shortURL=URLstr).order_by().distinct()
        if (len(selectedURL)==0):  #if an invalid URL is inputted
            notFound = True
    
    if len(selectedURL) != 0: #increments the number of visits to the URL by 1 if valid URL is inputted
        selectedURL[0].visits = selectedURL[0].visits + 1
        selectedURL[0].save()

    context = {
        'URLstr': URLstr,
        'notFound': notFound,
        'selectedURL': selectedURL,       
    }

    return render(request, 'longURL.html', context)



mysite/URL/templates/homePage.html


<head>
    <title>Homepage</title>
</head>


<body>
    <h1>---URL Shortener Homepage---</h1>

    <h3>Input URL extension below</h3>
    
    <h4>Note: If URL is 'www.example.com/long_URL_extension1234567890', please input only 'long_URL_extension1234567890'</h4>
    <h4>When entering short URL in URL bar, enter 'www.example.com/generated_shortened_URL'</h4>
    <form method="get">
        <input id="search_box" type="text" name="searchBox" placeholder='Input long URL'>
        <input type="submit" value="Submit" name="searchBtn">
    </form>

    {% if not duplicate %}
        {% if URLTyped %}
            <h3> You inputted {{searched}}</h3>
            <h4> Your short URL is {{selectedURL.0.shortURL}}</h4>
        {% endif %}
    {% endif %}

    {% if duplicate %}
        <h1>That URL has already been shortened to "{{selectedURL.0.shortURL}}"</h1>
    {% endif %}

</body>

mysite/URL/templates/longURL.html
<head>



</head>

<body>
    

    {% if notFound %}
        <h1>URL cannot be found</h1>

    {% endif %}
    {% if not notFound %}    
        <h1>'{{selectedURL.0.longURL}}' long URL found</h1>
        <h1>'{{selectedURL.0.shortURL}}' corresponding short URL found</h1>
        <h3>This URL was visited {{selectedURL.0.visits}} times.</h3>
    {% endif %}

    <a href="{% url 'URLs:URLhomepage'%}">Return to Homepage</a>

    

</body>